a = 2+2;
console.log(a);
b = 2*4;
console.log(b);
c = 2-1;
console.log(c);
d = "Hello " + "World";
console.log(d);
e = simpleString = "Hello world!";
console.log(e);
f = x = 5;
console.log(f);
f *= 3;
console.log(f);
compare = 5 == 5;
console.log(compare);
h = 5 < 7; 
console.log(h);
i= 10 != 11;
console.log(i);
j = 9 < 10 && 15 > 0;
console.log(j);
